### ISSUE TITLE
Preprocessing data

### ISSUE THREAD

**Issue by linhlpv** [ristea/cycle-transformer#1]
Hi,
Thank you so much about the great works!

As I know in many GAN based methods, normalize input to range -1 1 is a tip for stable training but I do not see norm func in your CT-dataset. Could you explain that why you did not use this, plz?

Thank you a lot and hope to hear from you soon.
Best,

**Comment by ristea** [comment]
Hi! We did normalization based on prior about data. In data/ct_dataset.py you can observe it at lines 31-32, 39-40.

**Comment by linhlpv** [comment]
hello. 
Thank for your reply. So is 1e3 global statistic param of your dataset? I want to know about its meaning.
Thank u.

**Comment by ristea** [comment]
The raw data are DICOM files in Hounsfield scale. The values for CTs are approximatively in [0, 3500]. This is the reason for that value.
