### ISSUE TITLE
Bug when using nn.DataParallel

### ISSUE THREAD

**Issue by linhlpv** [ristea/cycle-transformer#2]
I have tried to use nn.DataParallel for training on  multi GPUs. But I found a bug when adding nn.DataParallel on model
![image](https://user-images.githubusercontent.com/33130456/156607913-9afcc5e1-0e5e-4799-9151-90aa3b16a199.png)
Have you ever faced with this bug?
Thank you.
Best,

**Comment by ristea** [comment]
We did not try to run the model on multiple GPUs, so we did not encountered this bug.

**Comment by linhlpv** [comment]
Thank you. I have tried to fix it since yesterday but I still have not succeed. So that I decided that just run in single gpu :D
